### PR TITLE
cleanup and new navigation ideas

### PR DESCRIPTION
**Pull request by mneumegen**
Hey Tom,

I spent the evening messing around with a few ideas on how to improve the navigation on your documentation theme. This definitely isn't ready to be merged in, just seeing what you think.

What I've done:
- **Cleaned up the source code**: A lot of the code wasn't indented logically. In the process of fixing it up, I found a few missing closing tags on HTML elements, these could cause inconsistent behaviour between browsers.
- **Simplified the top nav logic**: I wanted to get rid of the data file for storing the top nav altogether but it's tricky with the external links. So what I tried to do is reduce the amount of loops and logic in your main nav. There was also a lot of repetition when outputting links. The code for an active link, non active link and link in a dropdown are all very similar so I put that logic in an include.
- **Moved the documentation files to collections***: The documentation for each product should be in a collections as it's a group of related documents. I wanted to reduce is the repetition of titles, urls and other metadata of these files in data files. The way it was makes it tricky to maintain as if you update the front matter you have to remember to update the datafile. I think all the metadata should live in the collection so everything is in one place and there's no repetition. I've added `_data/sub_navigation.yml` which contains the navigation headings (or I've called them categories) for each product. Then in each collection document there's a `category` field which indicates what category to populate it under and a `weight` which is the sort order.

Limitations: 
- I can't think of a nice way to implement the navigation on the news page. It looks like it's similar to the top navigation where it's just a set of links the user sets.
- I haven't got sub-sub categories working. There's a couple of ways that could work but I can think of anything super elegant.
- I haven't tested the PDF stuff. If you want to filter the nav based on web/pdf you could add the data to the front matter in the documents.

Anyway, hope this is useful for you :-)

### CODE REVIEW

**Comment by tomjoht** [comment]
Mike, thanks so much for checking out the theme and making updates. Give me a couple of days to dig into the changes here and see how you've improved things. 

One thing I would love for you to advise me on is links. My basic strategy was to use the urls.txt file to generate the right formatting, and then push that into a data file. Is there any way to do that kind of processing automatically each time the theme builds?

**Comment by mneumegen** [comment]
Anywhere you repeat code you should try and remove because there's a good chance that data will get out of sync. It's good you're generating the data files because it will help reduce that chance but it's another step you have to remember to do. 

I would take a slightly different approach and treat your collections as the one true source for the data. Then use includes (or you could create Jekyll plugins to make this even easier) to create helpers or shortcuts.

It looks like urls.txt is used to generate HTML links for data in the sidebar. All of this data is available from the collection document in version I did, so we can just create an include to generate the HTML link easily:

`_includes/quick_link.html`:

```
{% capture id %}/{{ include.id }}{% endcapture %}
{% assign doc = site[include.collection] | where: "id", id | first %}
<a href="{{ doc.url | prepend: site.baseurl }}">{{ doc.title }}</a>
```

Then we can use it on the site like this:

```
{% include quick_link.html collection="my_docs" id="mydoc_about" %}
```

Which outputs:

```
<a href="/documentation-theme-jekyll/mydoc_about/">About the theme author</a>
```

If you created a plugin you could even do something like this:

```
{{ quick_link "my_docs", "mydoc_about" }}
```

**Comment by tomjoht** [comment]
Thanks for providing this code. Let me experiment with it a bit. I am definitely eager to use includes for links since you get flagged about errors when the includes aren't there.

**Comment by tomjoht** [comment]
I checked out some of the updates a bit more. It's interesting to see the approach you took with the navigation. You definitely simplified things. However, when I ran `jekyll serve` I didn't see the sidebar appear. That's why I reverted the pull request there. I'll need to explore this a bit more. Did the sidebar appear when you built the site locally?

Also, I'm not sure I want to edit the weight of each page in each category. If you want to switch around your navigation order, you have to go into lots of different pages and update the category number. Isn't it easier just to see the sidebar items in one file?

**Comment by mneumegen** [comment]
Hey Tom,

It's definitely not ready to be merged in, I was just messing around with a couple of ideas at this point. If you want to try out my version I'd recommend just checking it out from my repo rather than merging and reverting it in yours.

Looks like I didn't have the index page in a collection which caused the sidebar to disappear. Fixed in the latest commit.

With the weight you can use decimals so you don't have to change multiple files. For example if you had:

Page A - weight: 1
Page B - weight: 2
Page C - weight: 3

And you wanted Page B to be first you could change its weight to 0.5. It might not be ideal but I can't see a perfect solution for this so it's always going to be some sort of compromise. In one hand it's easier to reorder the navigation in a data file but on the other, you end up duplicating a lot of the data.

**Pull request merged**
